# Change these first
owner: jpleasants # Your GitHub organization or username, where this repository lives
repo: plesk9 # The name of this repository
delay: 2000 # 2 seconds

sites:
  - name: Plesk 9
    url: https://plesk9.samitsolutions.com
    port: 8443
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: OBSN
    url: https://obsn.org
    maxResponseTime: 20000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Saffron Cary
    url: https://saffroncary.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Chaat Mandi NC
    url: https://chaatmandinc.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Maharaja NC
    url: https://maharajanc.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Thali RTP
    url: https://thalirtp.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: NC Spices
    url: https://ncspices.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Directed Facility Solutions
    url: https://directedfacilitysolutions.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: NCS Global Inc
    url: https://ncsglobalinc.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Park Life
    url: https://parklifecomm.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: March to The Polls
    url: https://marchtothepolls.org
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: MS Hubs
    url: https://mshubs.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Epec Solutions Inc
    url: https://epecsolutionsinc.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: May Flower Seafood
    url: https://mayflowerseafoodrm.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Veear Health
    url: https://veearhealth.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Origin Hubs
    url: https://originhubs.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Doorworks Company
    url: https://doorworkscompany.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Carolina Medical Care
    url: https://carolinamedicalcare.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Tekrek
    url: https://tekrek.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Chaska Indian Cuisine
    url: https://chaskaindiancuisine.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Tara Gems Galore
    url: https://taragemsgalorellc.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Saffron Durham
    url: https://saffrondurham.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Vata Vriksh
    url: https://vatavriksh.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Launch Morrisville
    url: https://LaunchMorrisville.org
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: Techlogyx
    url: https://techlogyx.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /plesk9
  logoUrl: https://samitpublic.blob.core.windows.net/download/sam-it-dots(1).png
  name: SAM IT Solutions
  theme: night
  introTitle: "**Status** page highlighting active incidents, current status of endpoints, and historical data."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  robotsText: "User-agent: * \n Disallow: /"

i18n:
  footer: ""

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
