# Change these first
owner: jpleasants # Your GitHub organization or username, where this repository lives
repo: plesk11 # The name of this repository
delay: 2000 # 2 seconds

sites:
  - name: plesk 11
    url: https://plesk11.samitsolutions.com
    port: 8443
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: marchtothepolls
    url: https://marchtothepolls.org
    maxResponseTime: 20000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: picklesandplay
    url: https://picklesandplay.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: tandooribitesdurham
    url: https://tandooribitesdurham.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: clintrialresearch
    url: https://clintrialresearch.com/
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: OBSN
    url: https://obsn.org
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: cmcbuildinginc
    url: https://cmcbuildinginc.com 
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: carolinaretinaeyecare
    url: https://carolinaretinaeyecare.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: samitsolutions
    url: https://samitsolutions.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: chaskaindiancuisine
    url: https://chaskaindiancuisine.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: clovencardamom
    url: https://clovencardamom.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: vascularwellness
    url: https://vascularwellness.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: tandooribites
    url: https://tandooribites.net
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: tandoorchapelhill
    url: https://tandoorchapelhill.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: africancaribbeanmarket
    url: https://africancaribbeanmarket.com/
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: chaatmandinc
    url: https://chaatmandinc.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: freshindianmarket
    url: https://freshindianmarket.com/
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: epecsolutionsinc
    url: https://epecsolutionsinc.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: carolinas
    url: https://carolinas.tie.org
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: raidentechgroup
    url: https://raidentechgroup.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: azitra
    url: https://azitra.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: harmonync
    url: https://harmonync.org
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: control-infotech
    url: https://control-infotech.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: campussafetyproducts
    url: https://campussafetyproducts.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403
  - name: campussafetyproducts
    url: https://campussafetyproducts.com
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 403

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /plesk11
  logoUrl: https://samitpublic.blob.core.windows.net/download/sam-it-dots(1).png
  name: SAM IT Solutions
  theme: night
  introTitle: "**Status** page highlighting active incidents, current status of endpoints, and historical data."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  robotsText: "User-agent: * \n Disallow: /"

i18n:
  footer: ""

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
